openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths:
  /layers:
    get:
      operationId: LayerStore_list
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Layer'
  /layers/create:
    post:
      operationId: LayerStore_create
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LayerCreateCommand'
  /layers/{id}:
    get:
      operationId: LayerStore_get
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Layer'
        '404':
          description: The server cannot find the requested resource.
components:
  schemas:
    ArrayRestrictions:
      type: object
      required:
        - value
      properties:
        min:
          type: number
        max:
          type: number
        value:
          $ref: '#/components/schemas/IfcxValueDescription'
    DataType:
      type: string
      enum:
        - Real
        - Boolean
        - Integer
        - String
        - DateTime
        - Enum
        - Array
        - Object
        - Relation
    EnumRestrictions:
      type: object
      required:
        - options
      properties:
        options:
          type: array
          items:
            type: string
    IfcxFile:
      type: object
      required:
        - header
        - schemas
        - data
      properties:
        header:
          $ref: '#/components/schemas/IfcxHeader'
        schemas:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IfcxSchema'
        data:
          type: array
          items:
            $ref: '#/components/schemas/IfcxNode'
    IfcxHeader:
      type: object
      required:
        - version
        - author
        - timestamp
      properties:
        version:
          type: string
        author:
          type: string
        timestamp:
          type: string
    IfcxNode:
      type: object
      required:
        - identifier
      properties:
        identifier:
          $ref: '#/components/schemas/path'
        children:
          type: object
          additionalProperties:
            type: string
            nullable: true
        inherits:
          type: object
          additionalProperties:
            type: string
            nullable: true
        attributes:
          type: object
          additionalProperties: {}
    IfcxSchema:
      type: object
      required:
        - value
      properties:
        uri:
          type: string
        value:
          $ref: '#/components/schemas/IfcxValueDescription'
    IfcxValueDescription:
      type: object
      required:
        - dataType
      properties:
        dataType:
          $ref: '#/components/schemas/DataType'
        inherits:
          type: array
          items:
            type: string
        quantityKind:
          $ref: '#/components/schemas/QuantityKind'
        enumRestrictions:
          $ref: '#/components/schemas/EnumRestrictions'
        arrayRestrictions:
          $ref: '#/components/schemas/ArrayRestrictions'
        objectRestrictions:
          $ref: '#/components/schemas/ObjectRestrictions'
        relationRestrictions:
          $ref: '#/components/schemas/RelationRestrictions'
    Layer:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    LayerCreateCommand:
      type: object
      required:
        - id
      properties:
        id:
          type: string
    ObjectRestrictions:
      type: object
      required:
        - values
      properties:
        values:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/IfcxValueDescription'
    QuantityKind:
      type: string
      enum:
        - Plane angle
        - Thermodynamic temperature
        - Electric current
        - Time
        - Frequency
        - Mass
        - Length
        - Linear velocity
        - Force
        - Pressure
        - Area
        - Energy
        - Power
        - Volume
    RelationRestrictions:
      type: object
      required:
        - type
      properties:
        type:
          type: string
    code:
      type: string
      pattern: </[A-Za-z0-9]+>
    path:
      type: string
      pattern: </[A-Za-z0-9_/.:]+>
